"""The free KQV suboperad and the realization functor ``F : KQV -> sarr``.

A ``KQVTerm`` is, *by construction*, a member of the suboperad generated by the
attention heads (``obs.generate``): a head generator ``Head``, an operadic
substitution ``Sub`` of terms into a head's inner boxes, or a lens tensor ``Par`` of
terms (width / multi-head).  ``realize`` is the functor
``F`` (the paper's ``R^-``), realizing a term as a ``SmoothArrangement`` using ONLY
dap's operad operations -- ``compose_seq`` (substitution = depth) and
``tensor_arrangements`` (lens tensor = width, used to bundle a head's children).

Consequently "this arrangement factors through the KQV suboperad" is exactly the
statement "it is ``realize(t)`` for some ``KQVTerm t``", checkable by tracing ``t``.
Nothing in this package builds a ``SmoothArrangement`` by any other means; an
experiment that needs something outside this algebra is a *finding*, not a patch.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple

from dap.arrangement import SmoothArrangement
from dap.wiring import compose_seq, tensor_arrangements

from .head import attention_head


class KQVTerm:
    """Base type.  Membership in the KQV suboperad is *being* a ``KQVTerm``."""


@dataclass(frozen=True)
class Head(KQVTerm):
    """A head generator of arity ``N`` over residual width ``E`` (``con.head``).

    ``N = 0`` is the prior box (``ex.zeroary``); ``d, d_v`` are the internal ranks
    (ignored when ``N = 0``).  ``sharp`` is the reactive vector space / optimizer.
    """

    N: int
    E: int
    d: int = 1
    d_v: int = 1
    sharp: object = None
    label: object = None

    def __post_init__(self):
        # the term algebra is total: an invalid generator cannot be constructed
        if self.N < 0:
            raise ValueError(f"Head arity N must be >= 0, got {self.N}")
        if self.E < 1:
            raise ValueError(f"Head residual width E must be >= 1, got {self.E}")
        if self.N >= 1 and (self.d < 1 or self.d_v < 1):
            raise ValueError("Head internal ranks d, d_v must be >= 1 when N >= 1")


@dataclass(frozen=True)
class Sub(KQVTerm):
    """Operadic substitution of ``children`` into the inner boxes of ``parent``.

    ``len(children)`` must equal ``parent.N`` (one subtree per inner box) and every
    child must share the residual width ``parent.E`` (``obs.residual``).
    """

    parent: Head
    children: Tuple[KQVTerm, ...]

    def __post_init__(self):
        if not isinstance(self.parent, Head) or self.parent.N < 1:
            raise ValueError("Sub.parent must be a Head of arity >= 1")
        if len(self.children) != self.parent.N:
            raise ValueError(
                f"Sub: expected {self.parent.N} children, got {len(self.children)}"
            )
        for c in self.children:
            if target_boxes(c) != 1:
                raise ValueError("Sub: each child must target a single box (not a lens tensor)")
            if width(c) != self.parent.E:
                raise ValueError("Sub: child residual width must match parent.E")


@dataclass(frozen=True)
class Par(KQVTerm):
    """Lens tensor (width) of terms: independent subsystems side by side.

    The second operad operation alongside substitution (``obs.generate``: composition
    is depth, the lens tensor is width / multi-head). A ``Par`` has ``len(parts)``
    target boxes, so it is a top-level combinator and may NOT be a ``Sub`` child
    (which needs a single-box target). All parts must share the residual width ``E``.
    """

    parts: Tuple[KQVTerm, ...]

    def __post_init__(self):
        if len(self.parts) < 1:
            raise ValueError("Par needs at least one part")
        E0 = width(self.parts[0])
        for p in self.parts:
            if width(p) != E0:
                raise ValueError("Par: all parts must share the residual width E")


def width(term: KQVTerm) -> int:
    """The residual width ``E`` shared by a term's target box(es)."""
    if isinstance(term, Head):
        return term.E
    if isinstance(term, Sub):
        return term.parent.E
    if isinstance(term, Par):
        return width(term.parts[0])
    raise TypeError(f"not a KQVTerm: {term!r}")


def target_boxes(term: KQVTerm) -> int:
    """Number of target boxes: 1 for a head/substitution; a lens tensor multiplies."""
    if isinstance(term, (Head, Sub)):
        return 1
    if isinstance(term, Par):
        return sum(target_boxes(p) for p in term.parts)
    raise TypeError(f"not a KQVTerm: {term!r}")


def open_boxes(term: KQVTerm) -> int:
    """Number of open inner boxes at the bottom of a term (its source arity)."""
    if isinstance(term, Head):
        return term.N
    if isinstance(term, Sub):
        return sum(open_boxes(c) for c in term.children)
    if isinstance(term, Par):
        return sum(open_boxes(p) for p in term.parts)
    raise TypeError(f"not a KQVTerm: {term!r}")


def realize(term: KQVTerm) -> SmoothArrangement:
    """The functor ``F``: realize a ``KQVTerm`` as a ``SmoothArrangement`` in ``sarr``.

    Uses only ``attention_head`` (the generator), ``compose_seq`` (substitution),
    and ``tensor_arrangements`` (the lens tensor bundling a head's children).
    """
    if isinstance(term, Head):
        return attention_head(
            term.N, term.E, term.d, term.d_v, sharp=term.sharp, label=term.label
        )
    if isinstance(term, Sub):
        parent = realize(term.parent)
        kids = [realize(c) for c in term.children]
        return compose_seq(tensor_arrangements(kids), parent)  # operadic substitution
    if isinstance(term, Par):
        return tensor_arrangements([realize(p) for p in term.parts])  # lens tensor (width)
    raise TypeError(f"realize expects a KQVTerm, got {type(term).__name__}")


# ---------------------------------------------------------------------------
# Convenience builders (still only Head / Sub -- the generating set).
# ---------------------------------------------------------------------------


def leaf(E, *, sharp=None, label=None) -> Head:
    """A bottom box: the 0-ary prior generator (``ex.zeroary``)."""
    return Head(0, E, sharp=sharp, label=label)


def flat(N, E, d, d_v, *, sharp=None, leaf_sharp=None) -> Sub:
    """A depth-1 closed system: one head over ``N`` prior leaves (the Stage-1 shape)."""
    return Sub(
        Head(N, E, d, d_v, sharp=sharp),
        tuple(leaf(E, sharp=leaf_sharp) for _ in range(N)),
    )


# ---------------------------------------------------------------------------
# Provenance: experiments must factor through KQV *and prove it* (codex audit).
# ---------------------------------------------------------------------------


def trace(term: KQVTerm, indent: int = 0) -> str:
    """A human-/auditor-readable rendering of the term tree (its provenance)."""
    pad = "  " * indent
    if isinstance(term, Head):
        kind = "leaf" if term.N == 0 else "head"
        return f"{pad}{kind}(N={term.N}, E={term.E})"
    if isinstance(term, Sub):
        lines = [f"{pad}sub(parent=head(N={term.parent.N}, E={term.parent.E}))"]
        lines += [trace(c, indent + 1) for c in term.children]
        return "\n".join(lines)
    if isinstance(term, Par):
        lines = [f"{pad}par(width={len(term.parts)})"]
        lines += [trace(p, indent + 1) for p in term.parts]
        return "\n".join(lines)
    raise TypeError(f"not a KQVTerm: {term!r}")


@dataclass(frozen=True)
class KQVSystem:
    """An experiment-ready system that *provably* factors through the suboperad.

    The contract for the experiment layer: build a ``KQVTerm``, wrap it as a
    ``KQVSystem``, and interpret ONLY ``system.arrangement`` (via ``Phiconf`` /
    ``Phiphase``).  A raw ``SmoothArrangement`` must never be interpreted in an
    experiment -- because then "it factors through KQV" would be unverifiable.  The
    system carries its originating term, so ``system.trace()`` exposes the exact
    generator tree for the auditor (this is the provenance the codex audit asked for).
    """

    term: KQVTerm

    def __post_init__(self):
        # provenance is enforced, not merely annotated: a system always wraps a real term
        if not isinstance(self.term, KQVTerm):
            raise TypeError(
                f"KQVSystem.term must be a KQVTerm, got {type(self.term).__name__}"
            )

    @property
    def arrangement(self) -> SmoothArrangement:
        """The realized arrangement ``F(term)`` -- the only thing experiments run."""
        return realize(self.term)

    def trace(self) -> str:
        """The provenance: the generator tree this system was built from."""
        return trace(self.term)
