"""The free KQV suboperad and the realization functor ``F : KQV -> sarr``.

A ``KQVTerm`` is, *by construction*, a member of the suboperad generated by the
attention heads (``obs.generate``): a head generator ``Head``, an operadic
substitution ``Sub`` of terms into a head's inner boxes, or a lens tensor ``Par`` of
terms (width / multi-head).  ``realize`` is the functor
``F`` (the paper's ``R^-``), realizing a term as a ``SmoothArrangement`` using ONLY
dap's operad operations -- ``compose_seq`` (substitution = depth) and
``tensor_arrangements`` (lens tensor = width, used to bundle a head's children).

Consequently "this arrangement factors through the KQV suboperad" is exactly the
statement "it is ``realize(t)`` for some ``KQVTerm t``", checkable by tracing ``t``.
Nothing in this package builds a ``SmoothArrangement`` by any other means; an
experiment that needs something outside this algebra is a *finding*, not a patch.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple

from dap.arrangement import SmoothArrangement
from dap.wiring import compose_seq, tensor_arrangements

from .cell import activation_cell
from .coincidence import coincidence_head
from .head import attention_head


class KQVTerm:
    """Base type.  Membership in the KQV suboperad is *being* a ``KQVTerm``."""


@dataclass(frozen=True)
class Head(KQVTerm):
    """A head generator of arity ``N`` over residual width ``E`` (``con.head``).

    ``N = 0`` is the prior box (``ex.zeroary``); ``d, d_v`` are the internal ranks
    (ignored when ``N = 0``).  ``sharp`` is the reactive vector space / optimizer.
    """

    N: int
    E: int
    d: int = 1
    d_v: int = 1
    sharp: object = None
    label: object = None

    def __post_init__(self):
        # the term algebra is total: an invalid generator cannot be constructed
        if self.N < 0:
            raise ValueError(f"Head arity N must be >= 0, got {self.N}")
        if self.E < 1:
            raise ValueError(f"Head residual width E must be >= 1, got {self.E}")
        if self.N >= 1 and (self.d < 1 or self.d_v < 1):
            raise ValueError("Head internal ranks d, d_v must be >= 1 when N >= 1")


@dataclass(frozen=True)
class Act(KQVTerm):
    """The activation-cell generator (Generator 3, ``SPEC.md``; route 2).

    An **arity-1** generator: a relaxable state box ``(R^E|R^E) -> (R^E|R^E)`` with
    carrier ``Q = R^k (+) R^{E x k}`` (fast ``z``, slow ``D``) and a block sharp.  It is
    a sibling of ``Head`` in the generating set, so the suboperad is now *enlarged*
    (heads + priors + cells).  ``k`` is the bottleneck rank; ``sharp`` is the reactive
    space / optimizer (default the block sharp); ``top_down`` adds the optional
    symmetric Rao--Ballard term to ``U``.  Its arity is fixed at 1 (``N`` below), so a
    cell is a legal ``Sub.parent`` (one child) and a legal ``Sub`` child (one box).
    """

    E: int
    k: int
    sharp: object = None
    top_down: bool = False
    prior_mu: object = None
    prior_lambda: float = 0.0
    label: object = None

    def __post_init__(self):
        if self.E < 1:
            raise ValueError(f"Act residual width E must be >= 1, got {self.E}")
        if self.k < 1:
            raise ValueError(f"Act code rank k must be >= 1, got {self.k}")

    @property
    def N(self) -> int:
        """Arity: a cell is arity-1 (one inner box on its wire)."""
        return 1


@dataclass(frozen=True)
class Coinc(KQVTerm):
    """The coincidence-head generator (SECOND order; ``kqv/coincidence.py``).

    Arity-``N`` like a head, but its upward read-out is a *second moment* of its children
    (``vech(P Pᵀ)``, ``P = Σ_j V h_j``), so it exposes co-activations a first-order pool is
    blind to. ``r`` is the feature rank; the carrier is ``(V, Wo, G)``. A sibling of ``Head``
    and ``Act`` in the generating set -- the first degree-2 generator (the moment hierarchy).
    """

    N: int
    E: int
    r: int = 1
    sharp: object = None
    label: object = None

    def __post_init__(self):
        if self.N < 1:
            raise ValueError(f"Coinc arity N must be >= 1, got {self.N}")
        if self.E < 1 or self.r < 1:
            raise ValueError("Coinc residual width E and feature rank r must be >= 1")


# The generating set of the suboperad: arity-N heads (incl. 0-ary priors), arity-1 cells,
# and arity-N coincidence heads (``obs.generate`` enlarged, ``SPEC.md`` "Term grammar").
# ``Sub.parent`` may be any of these with arity >= 1 -- a more general grammar, NOT a new op.
_GENERATORS = (Head, Act, Coinc)


@dataclass(frozen=True)
class Sub(KQVTerm):
    """Operadic substitution of ``children`` into the inner boxes of ``parent``.

    ``parent`` is any arity-``>= 1`` generator (a ``Head`` or, now, an ``Act`` cell --
    ``SPEC.md`` "Term grammar", a grammar change, not a new operation).
    ``len(children)`` must equal ``parent.N`` (one subtree per inner box) and every
    child must share the residual width ``parent.E`` (``obs.residual``).
    """

    parent: KQVTerm
    children: Tuple[KQVTerm, ...]

    def __post_init__(self):
        if not isinstance(self.parent, _GENERATORS) or self.parent.N < 1:
            raise ValueError("Sub.parent must be a generator (Head or Act) of arity >= 1")
        if len(self.children) != self.parent.N:
            raise ValueError(
                f"Sub: expected {self.parent.N} children, got {len(self.children)}"
            )
        for c in self.children:
            if target_boxes(c) != 1:
                raise ValueError("Sub: each child must target a single box (not a lens tensor)")
            if width(c) != self.parent.E:
                raise ValueError("Sub: child residual width must match parent.E")


@dataclass(frozen=True)
class Par(KQVTerm):
    """Lens tensor (width) of terms: independent subsystems side by side.

    The second operad operation alongside substitution (``obs.generate``: composition
    is depth, the lens tensor is width / multi-head). A ``Par`` has ``len(parts)``
    target boxes, so it is a top-level combinator and may NOT be a ``Sub`` child
    (which needs a single-box target). All parts must share the residual width ``E``.
    """

    parts: Tuple[KQVTerm, ...]

    def __post_init__(self):
        if len(self.parts) < 1:
            raise ValueError("Par needs at least one part")
        E0 = width(self.parts[0])
        for p in self.parts:
            if width(p) != E0:
                raise ValueError("Par: all parts must share the residual width E")


def width(term: KQVTerm) -> int:
    """The residual width ``E`` shared by a term's target box(es)."""
    if isinstance(term, (Head, Act, Coinc)):
        return term.E
    if isinstance(term, Sub):
        return term.parent.E
    if isinstance(term, Par):
        return width(term.parts[0])
    raise TypeError(f"not a KQVTerm: {term!r}")


def target_boxes(term: KQVTerm) -> int:
    """Number of target boxes: 1 for a head/cell/substitution; a lens tensor multiplies."""
    if isinstance(term, (Head, Act, Coinc, Sub)):
        return 1
    if isinstance(term, Par):
        return sum(target_boxes(p) for p in term.parts)
    raise TypeError(f"not a KQVTerm: {term!r}")


def open_boxes(term: KQVTerm) -> int:
    """Number of open inner boxes at the bottom of a term (its source arity)."""
    if isinstance(term, (Head, Coinc)):
        return term.N
    if isinstance(term, Act):
        return 1  # arity-1: a single inner box on the cell's wire
    if isinstance(term, Sub):
        return sum(open_boxes(c) for c in term.children)
    if isinstance(term, Par):
        return sum(open_boxes(p) for p in term.parts)
    raise TypeError(f"not a KQVTerm: {term!r}")


def realize(term: KQVTerm) -> SmoothArrangement:
    """The functor ``F``: realize a ``KQVTerm`` as a ``SmoothArrangement`` in ``sarr``.

    Uses only ``attention_head`` (the generator), ``compose_seq`` (substitution),
    and ``tensor_arrangements`` (the lens tensor bundling a head's children).
    """
    if isinstance(term, Head):
        return attention_head(
            term.N, term.E, term.d, term.d_v, sharp=term.sharp, label=term.label
        )
    if isinstance(term, Act):
        return activation_cell(
            term.E, term.k, sharp=term.sharp, top_down=term.top_down,
            prior_mu=term.prior_mu, prior_lambda=term.prior_lambda, label=term.label,
        )
    if isinstance(term, Coinc):
        return coincidence_head(term.N, term.E, term.r, sharp=term.sharp, label=term.label)
    if isinstance(term, Sub):
        parent = realize(term.parent)
        kids = [realize(c) for c in term.children]
        return compose_seq(tensor_arrangements(kids), parent)  # operadic substitution
    if isinstance(term, Par):
        return tensor_arrangements([realize(p) for p in term.parts])  # lens tensor (width)
    raise TypeError(f"realize expects a KQVTerm, got {type(term).__name__}")


# ---------------------------------------------------------------------------
# Convenience builders (still only Head / Sub -- the generating set).
# ---------------------------------------------------------------------------


def leaf(E, *, sharp=None, label=None) -> Head:
    """A bottom box: the 0-ary prior generator (``ex.zeroary``)."""
    return Head(0, E, sharp=sharp, label=label)


def flat(N, E, d, d_v, *, sharp=None, leaf_sharp=None) -> Sub:
    """A depth-1 closed system: one head over ``N`` prior leaves (the Stage-1 shape)."""
    return Sub(
        Head(N, E, d, d_v, sharp=sharp),
        tuple(leaf(E, sharp=leaf_sharp) for _ in range(N)),
    )


# ---------------------------------------------------------------------------
# Provenance: experiments must factor through KQV *and prove it* (codex audit).
# ---------------------------------------------------------------------------


def trace(term: KQVTerm, indent: int = 0) -> str:
    """A human-/auditor-readable rendering of the term tree (its provenance)."""
    pad = "  " * indent
    if isinstance(term, Head):
        kind = "leaf" if term.N == 0 else "head"
        return f"{pad}{kind}(N={term.N}, E={term.E})"
    if isinstance(term, Act):
        return f"{pad}act(k={term.k}, E={term.E})"
    if isinstance(term, Coinc):
        return f"{pad}coinc(N={term.N}, r={term.r}, E={term.E})"
    if isinstance(term, Sub):
        p = term.parent
        kind = (f"cell(k={p.k})" if isinstance(p, Act)
                else f"coinc(N={p.N},r={p.r})" if isinstance(p, Coinc)
                else f"head(N={p.N})")
        lines = [f"{pad}sub(parent={kind}, E={p.E})"]
        lines += [trace(c, indent + 1) for c in term.children]
        return "\n".join(lines)
    if isinstance(term, Par):
        lines = [f"{pad}par(width={len(term.parts)})"]
        lines += [trace(p, indent + 1) for p in term.parts]
        return "\n".join(lines)
    raise TypeError(f"not a KQVTerm: {term!r}")


@dataclass(frozen=True)
class KQVSystem:
    """An experiment-ready system that *provably* factors through the suboperad.

    The contract for the experiment layer: build a ``KQVTerm``, wrap it as a
    ``KQVSystem``, and interpret ONLY ``system.arrangement`` (via ``Phiconf`` /
    ``Phiphase``).  A raw ``SmoothArrangement`` must never be interpreted in an
    experiment -- because then "it factors through KQV" would be unverifiable.  The
    system carries its originating term, so ``system.trace()`` exposes the exact
    generator tree for the auditor (this is the provenance the codex audit asked for).
    """

    term: KQVTerm

    def __post_init__(self):
        # provenance is enforced, not merely annotated: a system always wraps a real term
        if not isinstance(self.term, KQVTerm):
            raise TypeError(
                f"KQVSystem.term must be a KQVTerm, got {type(self.term).__name__}"
            )

    @property
    def arrangement(self) -> SmoothArrangement:
        """The realized arrangement ``F(term)`` -- the only thing experiments run."""
        return realize(self.term)

    def trace(self) -> str:
        """The provenance: the generator tree this system was built from."""
        return trace(self.term)
